### ISSUE TITLE
Displaying only the detailed weather widget

### ISSUE THREAD

**Issue by d1g33k** [SilverAzide/Alien#1]
I use Rainmeter on a tablet as a dashboard and wish to only display the weather details on the Desktop by default on boot. What changes will be necessary in the ini file to attain the same?

**Comment by SilverAzide** [comment]
This is possible, but since the skin is not written to have the weather show first, there is going to be a minor cosmetic issue.  The weather data needs to be fetched from weather.com, so for a second or so, the skin is going to show empty data values, then refresh once the data arrives.

If this is OK, then one easy way you can achieve this is to add the following line in the `[Rainmeter]` section at the top of the file:
```ini
[Rainmeter]
...
OnRefreshAction=[!HideMeterGroup PageMain][!ShowMeterGroup PageWeather][!UpdateMeter *]
```
Another option is to let the skin show the first "page" briefly, then switch to the weather page after a delay of a couple seconds:
```ini
[Rainmeter]
...
OnRefreshAction=[!Delay 2000][!HideMeterGroup PageMain][!ShowMeterGroup PageWeather][!UpdateMeter *]
```
To properly display the weather first without needing the "OnRefreshAction" work-around would require a *lot* of changes.
